language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: vkkLb3pThXBVcdiDDQWr6E1C5Lj8cPYuTZ+RUJsnUKX56/UOr7AKeX8f1ZnnZ2Z7Icn/naLLUPyeSyqZ7CPFA3T3jjVBxltreCJqpFSA3RVzpGKebml1xqpBOF+1pKuSVcxtSFKf2YeTdTAM0vF4FVL1TL+Hs9KHmYtoG/E9hDP/6VgxUrvSI1SUwxJznYEFcDSpdZHsgP+FBVAx905ja01tgV0kH0/1urV05iX1EgGFsbDm7nUFvjpeZpEVTcfAO0KHOH4+1DAWbvrlGZHWNrYYqlgG4Aujra7dDBiGniFGZaEsRRufzBHVTHNWiShw0KKvCENz/uLPTuBo2V/CcHRtCjITJRK5pHjbrZzrLfb7iasOhJQGLzS186QiCZG3vkNBehbyDDMg7EQ65eIOLdgnPNRrpAGibGdDMHXbTHGkKaNm6SwqENAfpIZuDXBVPsawHBAYpDHxTESJSoFRY0407ZCuL7Y67b+VY0iz7JtVQwJzQ6VTS6Pe7yV4TpMR2kSxrJZ+z9IF2XesOJcRHVevWhCFqQ24D9SQVqlJjhM9qAi0Fq1WY+nP7ri74KpnHanj6vFcDpP/Vu6THs0VSwQaTGfjYOADouMh9bqAL4yPQn+xk/B3RzYWPSFCIUzwDa6n79tNmWBhwR4uDr6TkBirgtzdlPK3Hd0X31XI7vc=
  app: blooming-tundra-76491
  on:
    repo: echoise/projet
